language: node_js
node_js:
  - "14.15.1"
branches:
  only:
    - master
    - develop
    - /^fix-.*$/
install:
  - npm install
before_script:
  - cp .env.example .env.test.local
  - chmod +x travis-merge-script.sh
script:
  - npm run test:coverage && npm run test:reporter
after_success:
  - ./travis-merge-script.sh
